[package]
name = "zokrates_cli"
version = "0.2.0"
authors = ["Jacob Eberhardt <jacob.eberhardt@tu-berlin.de>", "Dennis Kuhnert <mail@kyroy.com>", "Thibaut Schaeffer <thibaut@schaeff.fr>"]
repository = "https://github.com/JacobEberhardt/ZoKrates.git"

[features]
default = ["libsnark"]
libsnark = ["zokrates_core/libsnark"]

[dependencies]
clap = "2.26.2"
bincode = "0.8.0"
regex = "0.2"
zokrates_core = { version = "0.2", path = "../zokrates_core" }
zokrates_fs_resolver = { version = "0.1", path = "../zokrates_fs_resolver"}

[dev-dependencies]
glob = "0.2.11"
assert_cli = "0.5"
serde_json = "1.0"

[[bin]]
name = "zokrates"
path = "src/bin.rs"
